#%RAML 1.0 DataType
properties:
  cap24hrChange:
      type: number
      example: -6.05
  long:
      type: string
      example: "Bitcoin"
  mktcap: 
      type: number
      example: 65173805891.25
  perc: 
      type: number
      example: 65173805891.25
  price: 
      type: number
      example: 65173805891.25
  shapeshift: 
      type: boolean
      example: true
  short:
      type: string
      example: "BTC"
  supply: 
      type: number
      example: 65173805891.25
  usdVolume: 
      type: number
      example: 65173805891.25
  volume: 
      type: number
      example: 65173805891.25
  vwapData: 
      type: number
      example: 65173805891.25
  vwapDataBTC: 
      type: number
      example: 65173805891.25