#%RAML 1.0 DataType
properties:
    altCap:
      type: number
      example: 0.0
    bitnodesCount:
      type: number
      example: 0.0
    btcCap:
      type: number
      example: 0.0
    btcPrice:
      type: number
      example: 0.0
    dom:
      type: number
      example: 0.0
    totalCap:
      type: number
      example: 0.0
    volumeAlt:
      type: number
      example: 0.0
    volumeBtc:
      type: number
      example: 0.0
    volumeTotal:
      type: number
      example: 0.0
    id:
      type: string
      example: "BTC"
    _id:
      type: string
      example: "c2f0fa55-495c-41e2-ad77-c66545b6d584"
    cap24hrChange:
      type: number
      example: 0.0
    display_name:
      type: string
      example: "Ethereum Classic"
    status:
      type: string
      example: "available"
    supply:
      type: number
      example: 0.0
    volume:
      type: number
      example: 0.0
    vwap_h24:
      type: number
      example: 0.0
    price_btc:
      type: number
      example: 0.0
    price_eth:
      type: number
      example: 0.0
    price_eur:
      type: number
      example: 0.0
    price_usd:
      type: number
      example: 0.0
    price_ltc:
      type: number
      example: 0.0
    price_zec:
      type: number
      example: 0.0
    market_cap:
      type: number
      example: 0.0
    type:
      type: string
      example: "cmc"
    price:
      type: number
      example: 0.0