#%RAML 1.0
title: Crypto API (CoinCap wrapper)
baseUri: http://localhost:8081/crypto
mediaType:  application/json
types:
  CoinCapFront: !include coincap-front.raml
  CoinCapPage: !include coincap-page-object.raml
  
/crypto:
    description: CoinCap wrapper
    get:
        description: GET coincap api front page response
        responses:
            200:
              body:
                application/json:
                  type: CoinCapFront[]
                  example: !include coincap-front-list.json
            404:
              description: Not found
    /page/{coin}:
      description: CoinCap wrapper
      get:
          description: GET coincap api coin page
          responses:
              200:
                body:
                  application/json:
                    type: CoinCapPage
                    example: !include coincap-page-object.json
              404:
                description: Not found
    